import './globals.css'
import { Barlow, Montserrat } from 'next/font/google'
import { Metadata } from 'next'
import MainLayout from '@/components/common/MainLayout'

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-barlow',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es' className={`${barlow.variable} ${montserrat.variable}`}>
      <body className='bg-background text-on-background'>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
