import './globals.css'
import { Barlow, Montserrat } from 'next/font/google'
import { Metadata } from 'next'
import SideBarWithNav from '@/components/common/SideBarWithNav'

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-barlow',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <body
        className={`${barlow.className} ${montserrat.variable} bg-background text-on-background`}>
        <SideBarWithNav title='Home' />
        {children}
      </body>
    </html>
  )
}
